### ISSUE TITLE
Surprise,  someone saw your work. I have a question about VB6 and dll files.

### ISSUE THREAD

**Issue by Astute-Paradox** [rlktradewright/tradewright-common#2]
I couldn't find a place to leave a comment, I guess this will do.
Hi. it is a little off topic but I had used the MSagents until about July 2019 and thanks to a microsoft update they no longer work. I still need to try to replace and re register  the dll but as near as I can tell the first time each MSagent is called there is a long pause and then the agent don't load and from then on there is no pause when trying to load each agent but it still don't load. I often wondered why it was so important for our big brother to not support vb6 and the agents but this seems like actively removing something. I wonder why. I figured you would at least know what I was talking about and any thoughts are welcome. Please give me some time to catch up on your code, I'm sure I need this but I am over my head a bit. Thank you.

Please enjoy what may well be the last performance by the MSagents. ( Remember MS Office Clippy? )   https://www.youtube.com/watch?v=AvebXxXn4Jg&list=FLGWmcx3HC5VYElp4NBhQdcw

**Comment by rlktradewright** [comment]
Ah well, these things happen!...

Actually I've never used Microsoft Agent (apart from turning off Clippy back in the day!), so I don't really know what value it has or what if does for you, except, presumably, Clippy-like things (which I have no use for).

Regarding VB6 and why Microsoft dropped it, I'm really not at all surprised by this, and I think it was the right decision. VB.Net was just such a vast improvement, there would have been very little reason to keep developing it. And to their credit, Microsoft have continued to ensure that VB6 programs run fine in current Windows versions.

As for the MSAgent, I presume Microsoft concluded that there isn't really enough demand to justify continued resourcing of the project: after all, everything to do with Clippy, Bob, etc has been roundly rejected by the anti-Microsoft brigade (which I am emphatically NOT a member of), and is a form of bad press that they (MS) can probably do without.

Frankly, VB6 drives me nuts: in particular the creaky old IDE, which was sort-of ok back in the 90s but is now a serious impediment to productivity. In contrast, working with Visual Studio 19 is a pleasure (on the whole). Having said that, I still have very significant swathes of VB6 software, as you've found, and this is primarily because of the very large effort required to port it over. I have actually done quite a lot of it, but there are still major components that I haven't done. The process has been hindered by the constantly changing target of .Net, and I'm really glad now that .Net Standard 2.0 is well-established, and the improvements in .Net Core 3.0 will be a game changer for me. But it's still a massive effort that I'll have to find time for somehow (reminder to self: must get back to it!).

Anyway, I'm not quite sure what your question is, if you have one, but if there's any way I (or rather my software can help) feel free to ask.
